blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/b7EwhxGJZY
    about: Please ask and answer questions here, not in DMS or issue.
  - name: Telegram
    url: https://t.me/implex_ltd
    about: Community backup.