[api]
port = 1337

[ratelimit]
api_max = 250
api_expiration = 1

[database]
username = "root"
password = "rootnikoontoplmao5245"
ip = "127.0.0.1"                  #"144.172.76.66"             
port = 88                         # 8000
